name: Group_26
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - altair
  - matplotlib
  - jupyterlab
  - pointblank
  - seaborn        
  - ucimlrepo      
  - pip

  - pip:
      - pandera
